"""Crear tabla advanced_features y actualizar market_metrics (opcional)

Revision ID: 9b661bde535a
Revises: 75a8b699eaaf
Create Date: 2025-12-04 14:39:44.947753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b661bde535a'
down_revision: Union[str, Sequence[str], None] = '75a8b699eaaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advanced_features',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        
        # Features de Lag y MA
        sa.Column('s11_lag_30d', sa.Numeric(), nullable=True),
        sa.Column('s11_ma_30d', sa.Numeric(), nullable=True),
        sa.Column('oil_wti_lag_30d', sa.Numeric(), nullable=True),
        # ... añadir todas las demás features de 's11_', 'oil_', 'ethanol_', etc.
        
        # Features de Spread y Correlación
        sa.Column('spread_11_5', sa.Numeric(), nullable=True),
        sa.Column('corr_11_5_30d', sa.Numeric(), nullable=True),
        
        # Features de Tiempo
        sa.Column('mes', sa.Integer(), nullable=True),
        sa.Column('dia_de_la_semana', sa.Integer(), nullable=True),
        
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('date') # Opcional: Asegurar que la fecha sea única
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advanced_features')
    # ### end Alembic commands ###